### ISSUE TITLE
Tensor contiguous error

### ISSUE THREAD

**Issue by WinKawaks** [craigleili/Sketch-R2CNN#1]
I found this error when I ran this program.
`
File "/vol/research/sketch/QuickDraw/Sketch-R2CNN-master/neuralline/rasterize.py", line 53, in backward
    rasterize_cuda.rasterize_backward(
RuntimeError: grad_intensities.is_contiguous() INTERNAL ASSERT FAILED at "/vol/research/sketch/QuickDraw/Sketch-R2CNN-master/neuralline/rasterize_cuda.cpp":73, please report a bug to PyTorch. grad_intensities must be contiguous
`

Then I modified the original program and solved the error like this:
`
        rasterize_cuda.rasterize_backward(
            grad_intensities.contiguous(),
            grad_line_map.contiguous(),
            ctx.saved_tensors[0], 
            ctx.saved_tensors[1], 
            ctx.saved_tensors[2], 
            ctx.saved_tensors[3].contiguous(), 
            ctx.saved_tensors[4].contiguous(), 
            ctx.img_size,
            ctx.thickness,
            ctx.eps)
        return None, grad_intensities, None, None, None, None
`

**Comment by craigleili** [comment]
Hello,

Thanks for reporting this. The error may be due to the difference of Pytorch versions, and yes, a fix should be like this.

All the best.

**Comment by ghost** [comment]
> I found this error when I ran this program.
> `File "/vol/research/sketch/QuickDraw/Sketch-R2CNN-master/neuralline/rasterize.py", line 53, in backward rasterize_cuda.rasterize_backward( RuntimeError: grad_intensities.is_contiguous() INTERNAL ASSERT FAILED at "/vol/research/sketch/QuickDraw/Sketch-R2CNN-master/neuralline/rasterize_cuda.cpp":73, please report a bug to PyTorch. grad_intensities must be contiguous`
> 
> Then I modified the original program and solved the error like this:
> `rasterize_cuda.rasterize_backward( grad_intensities.contiguous(), grad_line_map.contiguous(), ctx.saved_tensors[0], ctx.saved_tensors[1], ctx.saved_tensors[2], ctx.saved_tensors[3].contiguous(), ctx.saved_tensors[4].contiguous(), ctx.img_size, ctx.thickness, ctx.eps) return None, grad_intensities, None, None, None, None`

曲智宇，男，出生日期1993.8.15，微信账号文末，github账号winkawaks，邮箱547137393@qq.com，此人欠钱不还，已失联数月，如有认识此人的看到消息请与我联系，有重谢。
