### ISSUE TITLE
Error while using cpu

### ISSUE THREAD

**Issue by ghost** [craigleili/Sketch-R2CNN#2]
I am getting this error when I test my model using cpu.

RuntimeError: lines.type().is_cuda() ASSERT FAILED at neuralline/rasterize_cuda.cpp:43, please report a bug to PyTorch. lines must be a CUDA tensor (rasterize_forward at neuralline/rasterize_cuda.cpp:43)

frame #0: std::function<std::string ()>::operator()() const + 0x11 (0x7fce3ac75021 in venv/lib/python3.5/site-packages/torch/lib/libc10.so)
frame #1: c10::Error::Error(c10::SourceLocation, std::string const&) + 0x2a (0x7fce3ac748ea in venv/lib/python3.5/site-packages/torch/lib/libc10.so)
frame #2: rasterize_forward(at::Tensor, at::Tensor, at::Tensor, at::Tensor, at::Tensor, at::Tensor, int, float, float) + 0x123 (0x7fced9488eb5 in /tmp/torch_extensions/rasterize_cuda/rasterize_cuda.so)
frame #3: <unknown function> + 0x5dfdb (0x7fced94aefdb in /tmp/torch_extensions/rasterize_cuda/rasterize_cuda.so)
frame #4: <unknown function> + 0x5a5ee (0x7fced94ab5ee in /tmp/torch_extensions/rasterize_cuda/rasterize_cuda.so)
frame #5: <unknown function> + 0x556d9 (0x7fced94a66d9 in /tmp/torch_extensions/rasterize_cuda/rasterize_cuda.so)
frame #6: <unknown function> + 0x55c83 (0x7fced94a6c83 in /tmp/torch_extensions/rasterize_cuda/rasterize_cuda.so)
frame #7: <unknown function> + 0x45fd8 (0x7fced9496fd8 in /tmp/torch_extensions/rasterize_cuda/rasterize_cuda.so)
frame #8: PyCFunction_Call + 0x77 (0x4ea7d7 in venv/bin/python)
frame #9: PyEval_EvalFrameEx + 0x614 (0x53be14 in venv/bin/python)
frame #10: PyEval_EvalCodeEx + 0x13b (0x545b9b in venv/bin/python)
frame #11: venv/bin/python() [0x4ec948]
frame #12: PyObject_Call + 0x47 (0x5bfbe7 in venv/bin/python)
frame #13: PyEval_CallObjectWithKeywords + 0x30 (0x531100 in venv/bin/python)
frame #14: THPFunction_apply(_object*, _object*) + 0x581 (0x7fce751b3ab1 in venv/lib/python3.5/site-packages/torch/lib/libtorch_python.so)
frame #15: PyCFunction_Call + 0x4f (0x4ea7af in venv/bin/python)
frame #16: PyEval_EvalFrameEx + 0x614 (0x53be14 in venv/bin/python)
frame #17: PyEval_EvalCodeEx + 0x13b (0x545b9b in venv/bin/python)
frame #18: venv/bin/python() [0x4ec8d3]
frame #19: PyObject_Call + 0x47 (0x5bfbe7 in venv/bin/python)
frame #20: venv/bin/python() [0x4fc4be]
frame #21: PyObject_Call + 0x47 (0x5bfbe7 in venv/bin/python)
frame #22: venv/bin/python() [0x599546]
frame #23: PyObject_Call + 0x47 (0x5bfbe7 in venv/bin/python)
frame #24: PyEval_EvalFrameEx + 0x4edf (0x5406df in venv/bin/python)
frame #25: PyEval_EvalFrameEx + 0x4b14 (0x540314 in venv/bin/python)
frame #26: PyEval_EvalFrameEx + 0x4b14 (0x540314 in venv/bin/python)
frame #27: PyEval_EvalFrameEx + 0x4b14 (0x540314 in venv/bin/python)
frame #28: venv/bin/python() [0x5452af]
frame #29: PyEval_EvalFrameEx + 0x5511 (0x540d11 in venv/bin/python)
frame #30: venv/bin/python() [0x544d73]
frame #31: PyEval_EvalCode + 0x1f (0x545a4f in venv/bin/python)
frame #32: venv/bin/python() [0x54f465]
frame #33: PyCFunction_Call + 0x4f (0x4ea7af in venv/bin/python)
frame #34: PyEval_EvalFrameEx + 0x614 (0x53be14 in venv/bin/python)
frame #35: _PyGen_Send + 0x133 (0x4ee383 in venv/bin/python)
frame #36: PyEval_EvalFrameEx + 0x5d15 (0x541515 in venv/bin/python)
frame #37: _PyGen_Send + 0x133 (0x4ee383 in venv/bin/python)
frame #38: PyEval_EvalFrameEx + 0x5d15 (0x541515 in venv/bin/python)
frame #39: _PyGen_Send + 0x133 (0x4ee383 in venv/bin/python)
frame #40: PyEval_EvalFrameEx + 0x4cf6 (0x5404f6 in venv/bin/python)
frame #41: PyEval_EvalFrameEx + 0x4b14 (0x540314 in venv/bin/python)
frame #42: PyEval_EvalFrameEx + 0x4b14 (0x540314 in venv/bin/python)
frame #43: PyEval_EvalCodeEx + 0x13b (0x545b9b in venv/bin/python)
frame #44: venv/bin/python() [0x4ec9e7]
frame #45: PyObject_Call + 0x47 (0x5bfbe7 in venv/bin/python)
frame #46: PyEval_EvalFrameEx + 0x2534 (0x53dd34 in venv/bin/python)
frame #47: venv/bin/python() [0x5452af]
frame #48: PyEval_EvalFrameEx + 0x5511 (0x540d11 in venv/bin/python)
frame #49: venv/bin/python() [0x5480af]
frame #50: PyCFunction_Call + 0x106 (0x4ea866 in venv/bin/python)
frame #51: PyEval_EvalFrameEx + 0x6d60 (0x542560 in venv/bin/python)
frame #52: venv/bin/python() [0x544d73]
frame #53: PyEval_EvalFrameEx + 0x5511 (0x540d11 in venv/bin/python)
frame #54: venv/bin/python() [0x5452af]
frame #55: PyEval_EvalFrameEx + 0x5511 (0x540d11 in venv/bin/python)
frame #56: venv/bin/python() [0x5480af]
frame #57: PyCFunction_Call + 0x106 (0x4ea866 in venv/bin/python)
frame #58: PyEval_EvalFrameEx + 0x6d60 (0x542560 in venv/bin/python)
frame #59: venv/bin/python() [0x544d73]
frame #60: PyEval_EvalFrameEx + 0x5511 (0x540d11 in venv/bin/python)
frame #61: venv/bin/python() [0x5452af]
frame #62: PyEval_EvalFrameEx + 0x5511 (0x540d11 in venv/bin/python)
frame #63: venv/bin/python() [0x5480af]

**Comment by craigleili** [comment]
Hello,

A GPU is required for running the code, mainly due to the rasterization module.

All the best.
